<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cassandra" nsURI="http://cassandra.mortadelo.istr.unican.es"
    nsPrefix="cassandra">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="keySpaces" upperBound="-1"
        eType="#//KeySpace" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeySpace" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="columnFamilies" upperBound="-1"
        eType="#//ColumnFamily" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColumnFamily" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="#//Column" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexes" upperBound="-1"
        eType="#//Index" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Table" eSuperTypes="#//ColumnFamily"/>
  <eClassifiers xsi:type="ecore:EClass" name="MaterializedView" eSuperTypes="#//ColumnFamily">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseTable" lowerBound="1"
        eType="#//Table"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Column" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Type"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keys" upperBound="-1" eType="#//Key"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//PrimitiveType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Collection" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//PrimitiveType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collectionType" lowerBound="1"
        eType="#//CollectionType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tuple" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="types" upperBound="-1"
        eType="#//PrimitiveType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserDefinedType" eSuperTypes="#//Type #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
        eType="#//Field" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Field" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Type"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Key">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PartitionKey" eSuperTypes="#//Key"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClusteringKey" eSuperTypes="#//Key"/>
  <eClassifiers xsi:type="ecore:EClass" name="Index" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="#//Column"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CollectionType">
    <eLiterals name="MAP"/>
    <eLiterals name="SET" value="1"/>
    <eLiterals name="LIST" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PrimitiveType">
    <eLiterals name="TINYINT"/>
    <eLiterals name="SMALLINT" value="1"/>
    <eLiterals name="INT" value="2"/>
    <eLiterals name="BIGINT" value="3"/>
    <eLiterals name="VARINT" value="4"/>
    <eLiterals name="FLOAT" value="5"/>
    <eLiterals name="DOUBLE" value="6"/>
    <eLiterals name="DECIMAL" value="7"/>
    <eLiterals name="TEXT" value="8"/>
    <eLiterals name="VARCHAR" value="9"/>
    <eLiterals name="ASCII" value="10"/>
    <eLiterals name="TIMESTAMP" value="11"/>
    <eLiterals name="DATE" value="12"/>
    <eLiterals name="TIME" value="13"/>
    <eLiterals name="UUID" value="14"/>
    <eLiterals name="TIMEUUID" value="15"/>
    <eLiterals name="BOOLEAN" value="16"/>
    <eLiterals name="BLOB" value="17"/>
    <eLiterals name="INET" value="18"/>
    <eLiterals name="COUNTER" value="19"/>
  </eClassifiers>
</ecore:EPackage>
