<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="documentDataModel" nsURI="http://documentDataModel.mortadelo.istr.unican.es"
    nsPrefix="documentDataModel">
  <eClassifiers xsi:type="ecore:EClass" name="DocumentDataModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="collections" upperBound="-1"
        eType="#//Collection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Collection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" lowerBound="1" eType="#//Document"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexes" upperBound="-1"
        eType="#//Index" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Field" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Index">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" lowerBound="1"
        upperBound="-1" eType="#//Field"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Document" eSuperTypes="#//Field">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
        eType="#//Field" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveField" eSuperTypes="#//Field">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//PrimitiveType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayField" eSuperTypes="#//Field">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Field"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PrimitiveType">
    <eLiterals name="INT"/>
    <eLiterals name="FLOAT" value="1"/>
    <eLiterals name="TEXT" value="2"/>
    <eLiterals name="DATE" value="3"/>
    <eLiterals name="TIMESTAMP" value="4"/>
    <eLiterals name="BOOLEAN" value="5"/>
    <eLiterals name="ID" value="6"/>
  </eClassifiers>
</ecore:EPackage>
