/*
 * generated by Xtext 2.13.0
 */
package es.unican.istr.mortadelo.gdm.lang.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class GdmLangWebModule extends AbstractGdmLangWebModule {
}
