/*
 * generated by Xtext 2.13.0
 */
package es.unican.istr.mortadelo.gdm.lang


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class GdmLangStandaloneSetup extends GdmLangStandaloneSetupGenerated {

	def static void doSetup() {
		new GdmLangStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
