/*
 * generated by Xtext 2.13.0
 */
package es.unican.istr.mortadelo.gdm.lang


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class GdmLangRuntimeModule extends AbstractGdmLangRuntimeModule {
}
