/*
 * generated by Xtext 2.13.0
 */
package es.unican.istr.mortadelo.gdm.lang.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class GdmLangProposalProvider extends AbstractGdmLangProposalProvider {
}
