/*
 * generated by Xtext 2.13.0
 */
package es.unican.istr.mortadelo.gdm.lang.tests

import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(GdmLangInjectorProvider)
class GdmLangParsingTest {
//	@Inject
//	ParseHelper<Model> parseHelper
	
	@Test
	def void loadModel() {
	}
}
